overrides:
  '@babel/plugin-transform-modules-systemjs@>=7.12.0 <=7.29.3': '>=7.29.4'
  '@xmldom/xmldom@<0.8.13': '>=0.8.13'
  brace-expansion@>=5.0.0 <5.0.6: '>=5.0.6'
  fast-xml-builder@<=1.1.6: '>=1.1.7'
  fast-xml-builder@=1.1.5: '>=1.1.6'
  fast-xml-parser@<5.7.0: '>=5.7.0'
  fast-xml-parser@>=4.0.0-beta.3 <=5.5.6: '>=5.5.7'
  qs@>=6.11.1 <=6.15.1: '>=6.15.2'
  uuid@<14.0.0: '>=14.0.0'
