overrides:
  body-parser@<1.20.6: '>=1.20.6'
  brace-expansion@<1.1.16: '>=1.1.16'
  brace-expansion@<=5.0.7: '>=5.0.8'
  brace-expansion@>=3.0.0 <5.0.7: '>=5.0.7'
  fast-xml-parser@<5.7.0: '>=5.7.0'
  js-yaml@>=5.0.0 <=5.2.1: '>=5.2.2'
  qs@>=6.11.1 <=6.15.1: '>=6.15.2'
  typeorm@<0.3.31: '>=0.3.31'
  uuid@<11.1.1: '>=11.1.1'
  ws@>=7.0.0 <7.5.11: '>=7.5.11'
